### ISSUE TITLE
mistake at Lis3dh_Init?

### ISSUE THREAD

**Issue by arnedebrabanter** [guusleenders/EFM32-RN2483-LoRa-Node#4]
// Enable BDU, disable high resolution
	wBuffer[0] = LIS3DH_REG_CTRL4;
	wBuffer[1] = 0x08; 
	if(!IIC_WriteBuffer(LIS3DH_IIC_ADDRESS, wBuffer, 2)){
        return false;
}
According the datasheet is enabling BDU and disabling High resolution, writing 0x80 instead of 0x08?

**Comment by geoffreyottoy** [comment]
Comment is indeed erroneous. It has been corrected.
